import riot from 'riot';
import CcdaSection from './ccda-section.riot';
import Header from './header.riot';
import Name from './name.riot';
import Nonxml from './nonxml.riot';
import Panel from './panel.riot';
import PreferenceSection from './preference-section.riot';
import Preferences from './preferences.riot';
import Raw from './raw.riot';
import Allergies from './sections/allergies.riot';
import CarePlan from './sections/care-plan.riot';
import ChiefComplaint from './sections/chief-complaint.riot';
import Demographics from './sections/demographics.riot';
import Empty from './sections/empty.riot';
import Encounters from './sections/encounters.riot';
import FunctionalStatus from './sections/functional-status.riot';
import Generic from './sections/generic.riot';
import ImmunizationDeclines from './sections/immunization_declines.riot';
import Immunizations from './sections/immunizations.riot';
import Instructions from './sections/instructions.riot';
import Medications from './sections/medications.riot';
import Problems from './sections/problems.riot';
import Procedures from './sections/procedures.riot';
import Results from './sections/results.riot';
import SmokingStatus from './sections/smoking-status.riot';
import Vitals from './sections/vitals.riot';
import Sialia from './sialia.riot';

riot.register('sialia', Sialia);
riot.register('app-header', Header);
riot.register('preferences', Preferences);
riot.register('preference-section', PreferenceSection);
riot.register('panel', Panel);
riot.register('ccda-section', CcdaSection);
riot.register('raw', Raw);
riot.register('name', Name);
riot.register('nonxml', Nonxml);
riot.register('empty', Empty);
riot.register('generic', Generic);
riot.register('demographics', Demographics);
riot.register('allergies', Allergies);
riot.register('care-plan', CarePlan);
riot.register('chief-complaint', ChiefComplaint);
riot.register('encounters', Encounters);
riot.register('functional-status', FunctionalStatus);
riot.register('immunization-declines', ImmunizationDeclines);
riot.register('immunizations', Immunizations);
riot.register('instructions', Instructions);
riot.register('medications', Medications);
riot.register('problems', Problems);
riot.register('procedures', Procedures);
riot.register('results', Results);
riot.register('smoking-status', SmokingStatus);
riot.register('vitals', Vitals);
