name: Pull Request

on:
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        permissions:
            contents: read
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24.x'
                  cache: 'npm'
            - name: Configure NPM authentication
              if: ${{ env.NPM_TOKEN != '' }}
              run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
            - name: npm ci
              run: npm ci --ignore-scripts
            - name: Lint
              run: npm run lint
